name: Terraform

on:
  push:
    branches:
      - localtest

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var-file=environments/dev.tfvars

        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file=environments/dev.tfvars

        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}